baseURL: ""
languageCode: "zh-cn"
defaultContentLanguage: "zh"
theme: "kiera"

paginate: 3
summaryLength: 30
enableEmoji: true
pygmentsCodeFences: true
googleAnalytics: "UA-37594072-1"

languages:
    zh:
        title: "Alex Chi"
        tagline: "一位图形学爱好者的唠叨"
    en:
        title: "Alex Chi"
        tagline: "Chatter from a computer graphics fan"

author:
    name: "Alex Chi"
    #categories: "/categories"
    #tags: "/tags"
    user: "/pages/about-me"
    github: "alexchicn"
    gitlab: "alexchicn"
    twitter: "alexchicn"
    linkedin: "jixingcn"
    email: "mailto:alexchicn@gmail.com"

params:
    favicon:
        #ico: "images/favicon.ico"  # path to a .ico to use as favicon
        png: "https://s.gravatar.com/avatar/acf66434234f9fa7785e80d79d880a54?s=80"

markup:
    #defaultMarkdownHandler: goldmark
    #defaultMarkdownHandler: blackfriday
    #defaultMarkdownHandler: mmark
    tableOfContents:
        startLevel: 1
        endLevel: 2
        ordered: false
    goldmark:
        extensions:
            definitionList: true
            footnote: true
            linkify: true
            strikethrough: true
            table: true
            taskList: true
            typographer: true
            katex: true
        parser:
            attribute: true
            autoHeadingID: true
            autoHeadingIDType: github
        renderer:
            hardWraps: false
            unsafe: false
            xhtml: false

sitemap:
    changefreq: "weekly"
    filename: "sitemap.xml"
    priority: 0.5
